<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 01: Introduction to Statistical Decision Theory – STA 313 1.0</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ea1971949f186b5d7ecce1fd3cf000e4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">STA 313 1.0</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html#course-overview"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html#weekly-lessons"> 
<span class="menu-text">Weekly Lessons</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html#assessment"> 
<span class="menu-text">Assessment</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../index.html#reference"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-statistical-decision-theory" id="toc-introduction-to-statistical-decision-theory" class="nav-link active" data-scroll-target="#introduction-to-statistical-decision-theory">Introduction to Statistical Decision Theory</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  </ul></li>
  <li><a href="#opening-problem" id="toc-opening-problem" class="nav-link" data-scroll-target="#opening-problem">1. Opening problem</a>
  <ul class="collapse">
  <li><a href="#a-cricket-decision-before-the-theory" id="toc-a-cricket-decision-before-the-theory" class="nav-link" data-scroll-target="#a-cricket-decision-before-the-theory">A cricket decision before the theory</a>
  <ul class="collapse">
  <li><a href="#think-for-one-minute" id="toc-think-for-one-minute" class="nav-link" data-scroll-target="#think-for-one-minute">Think for one minute</a></li>
  <li><a href="#class-discussion" id="toc-class-discussion" class="nav-link" data-scroll-target="#class-discussion">Class discussion</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#what-is-statistical-decision-theory" id="toc-what-is-statistical-decision-theory" class="nav-link" data-scroll-target="#what-is-statistical-decision-theory">2. What is statistical decision theory?</a>
  <ul class="collapse">
  <li><a href="#core-decision-structure" id="toc-core-decision-structure" class="nav-link" data-scroll-target="#core-decision-structure">Core decision structure</a></li>
  </ul></li>
  <li><a href="#anatomy-of-a-decision-problem" id="toc-anatomy-of-a-decision-problem" class="nav-link" data-scroll-target="#anatomy-of-a-decision-problem">3. Anatomy of a decision problem</a>
  <ul class="collapse">
  <li><a href="#decision-alternatives" id="toc-decision-alternatives" class="nav-link" data-scroll-target="#decision-alternatives">3.1 Decision alternatives</a>
  <ul class="collapse">
  <li><a href="#cricket-example" id="toc-cricket-example" class="nav-link" data-scroll-target="#cricket-example">Cricket example</a></li>
  <li><a href="#quick-question" id="toc-quick-question" class="nav-link" data-scroll-target="#quick-question">Quick question</a></li>
  </ul></li>
  <li><a href="#states-of-nature" id="toc-states-of-nature" class="nav-link" data-scroll-target="#states-of-nature">3.2 States of nature</a>
  <ul class="collapse">
  <li><a href="#cricket-example-1" id="toc-cricket-example-1" class="nav-link" data-scroll-target="#cricket-example-1">Cricket example</a></li>
  <li><a href="#athletics-example" id="toc-athletics-example" class="nav-link" data-scroll-target="#athletics-example">Athletics example</a></li>
  <li><a href="#volleyball-example" id="toc-volleyball-example" class="nav-link" data-scroll-target="#volleyball-example">Volleyball example</a></li>
  </ul></li>
  <li><a href="#consequences" id="toc-consequences" class="nav-link" data-scroll-target="#consequences">3.3 Consequences</a></li>
  </ul></li>
  <li><a href="#the-four-step-decision-theory-approach" id="toc-the-four-step-decision-theory-approach" class="nav-link" data-scroll-target="#the-four-step-decision-theory-approach">4. The four-step decision-theory approach</a>
  <ul class="collapse">
  <li><a href="#basic-decision-structure" id="toc-basic-decision-structure" class="nav-link" data-scroll-target="#basic-decision-structure">Basic decision structure</a></li>
  </ul></li>
  <li><a href="#cricket-example-final-over-bowling-decision" id="toc-cricket-example-final-over-bowling-decision" class="nav-link" data-scroll-target="#cricket-example-final-over-bowling-decision">5. Cricket example: final-over bowling decision</a>
  <ul class="collapse">
  <li><a href="#identify-the-components" id="toc-identify-the-components" class="nav-link" data-scroll-target="#identify-the-components">Identify the components</a>
  <ul class="collapse">
  <li><a href="#decision-alternatives-1" id="toc-decision-alternatives-1" class="nav-link" data-scroll-target="#decision-alternatives-1">Decision alternatives</a></li>
  <li><a href="#states-of-nature-1" id="toc-states-of-nature-1" class="nav-link" data-scroll-target="#states-of-nature-1">States of nature</a></li>
  <li><a href="#consequence" id="toc-consequence" class="nav-link" data-scroll-target="#consequence">Consequence</a></li>
  </ul></li>
  <li><a href="#how-to-read-the-table" id="toc-how-to-read-the-table" class="nav-link" data-scroll-target="#how-to-read-the-table">How to read the table</a>
  <ul class="collapse">
  <li><a href="#stop-and-interpret" id="toc-stop-and-interpret" class="nav-link" data-scroll-target="#stop-and-interpret">Stop and interpret</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#payoff-and-loss-formulations" id="toc-payoff-and-loss-formulations" class="nav-link" data-scroll-target="#payoff-and-loss-formulations">6. Payoff and loss formulations</a>
  <ul class="collapse">
  <li><a href="#cricket-as-a-loss-problem" id="toc-cricket-as-a-loss-problem" class="nav-link" data-scroll-target="#cricket-as-a-loss-problem">Cricket as a loss problem</a></li>
  <li><a href="#cricket-as-a-payoff-problem" id="toc-cricket-as-a-payoff-problem" class="nav-link" data-scroll-target="#cricket-as-a-payoff-problem">Cricket as a payoff problem</a></li>
  </ul></li>
  <li><a href="#athletics-example-pacing-strategy-in-a-1500-m-race" id="toc-athletics-example-pacing-strategy-in-a-1500-m-race" class="nav-link" data-scroll-target="#athletics-example-pacing-strategy-in-a-1500-m-race">7. Athletics example: pacing strategy in a 1500 m race</a>
  <ul class="collapse">
  <li><a href="#class-questions" id="toc-class-questions" class="nav-link" data-scroll-target="#class-questions">Class questions</a></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a></li>
  <li><a href="#the-same-athletics-problem-using-a-payoff" id="toc-the-same-athletics-problem-using-a-payoff" class="nav-link" data-scroll-target="#the-same-athletics-problem-using-a-payoff">The same athletics problem using a payoff</a></li>
  </ul></li>
  <li><a href="#volleyball-example-1" id="toc-volleyball-example-1" class="nav-link" data-scroll-target="#volleyball-example-1">8. Volleyball example</a></li>
  <li><a href="#formulating-a-decision-problem" id="toc-formulating-a-decision-problem" class="nav-link" data-scroll-target="#formulating-a-decision-problem">9. Formulating a decision problem</a>
  <ul class="collapse">
  <li><a href="#template" id="toc-template" class="nav-link" data-scroll-target="#template">Template</a>
  <ul class="collapse">
  <li><a href="#decision-maker" id="toc-decision-maker" class="nav-link" data-scroll-target="#decision-maker">Decision maker</a></li>
  <li><a href="#alternatives" id="toc-alternatives" class="nav-link" data-scroll-target="#alternatives">Alternatives</a></li>
  <li><a href="#states-of-nature-2" id="toc-states-of-nature-2" class="nav-link" data-scroll-target="#states-of-nature-2">States of nature</a></li>
  <li><a href="#consequences-1" id="toc-consequences-1" class="nav-link" data-scroll-target="#consequences-1">Consequences</a></li>
  <li><a href="#available-information" id="toc-available-information" class="nav-link" data-scroll-target="#available-information">Available information</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#activity" id="toc-activity" class="nav-link" data-scroll-target="#activity">10. Student activity</a>
  <ul class="collapse">
  <li><a href="#minute-activity-volleyball-serving-decision" id="toc-minute-activity-volleyball-serving-decision" class="nav-link" data-scroll-target="#minute-activity-volleyball-serving-decision">8-minute activity: Volleyball serving decision</a>
  <ul class="collapse">
  <li><a href="#work-in-pairs" id="toc-work-in-pairs" class="nav-link" data-scroll-target="#work-in-pairs">Work in pairs</a></li>
  </ul></li>
  <li><a href="#suggested-answers" id="toc-suggested-answers" class="nav-link" data-scroll-target="#suggested-answers">Suggested answers</a></li>
  </ul></li>
  <li><a href="#why-the-distinction-matters" id="toc-why-the-distinction-matters" class="nav-link" data-scroll-target="#why-the-distinction-matters">11. Why the distinction matters</a>
  <ul class="collapse">
  <li><a href="#remember" id="toc-remember" class="nav-link" data-scroll-target="#remember">Remember</a></li>
  </ul></li>
  <li><a href="#exit-check" id="toc-exit-check" class="nav-link" data-scroll-target="#exit-check">12. Exit check</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul></li>
  <li><a href="#after-class" id="toc-after-class" class="nav-link" data-scroll-target="#after-class">After class</a>
  <ul class="collapse">
  <li><a href="#independent-learning" id="toc-independent-learning" class="nav-link" data-scroll-target="#independent-learning">Independent learning</a></li>
  <li><a href="#next-week" id="toc-next-week" class="nav-link" data-scroll-target="#next-week">Next week</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 01: Introduction to Statistical Decision Theory</h1>
<p class="subtitle lead">STA 313 1.0</p>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<p><a href="../index.html" class="btn btn-secondary">← Back to course homepage</a></p>
<div class="section-kicker">
<p>WEEK 01 · 60 MINUTES</p>
</div>
<section id="introduction-to-statistical-decision-theory" class="level1">
<h1>Introduction to Statistical Decision Theory</h1>
<p>A decision problem begins before any calculation is made. We first identify <strong>what can be chosen</strong>, <strong>what is uncertain</strong>, and <strong>what consequence follows from each action-state combination</strong>.</p>
<p>This first lesson focuses on the basic structure of a statistical decision problem. We will not yet use Maximax, Maximin, expected monetary value, or Bayesian decision rules. Those come in later weeks.</p>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>By the end of this lesson, you should be able to:</p>
<ol type="1">
<li>explain why decision theory is useful when future outcomes are not fully known;</li>
<li>distinguish a <strong>decision alternative</strong> from a <strong>state of nature</strong>;</li>
<li>identify the <strong>consequence</strong> associated with an action-state combination;</li>
<li>construct and interpret a simple <strong>payoff or loss table</strong>; and</li>
<li>describe the four basic steps in the decision-theory approach.</li>
</ol>
<div class="note">
<p><strong>Week 1 focus.</strong> Decision problems, alternatives, states of nature, consequences, payoff/loss tables, and the basic steps in the decision-theory approach.</p>
</div>
<hr>
</section>
</section>
<section id="opening-problem" class="level1">
<h1>1. Opening problem</h1>
<section id="a-cricket-decision-before-the-theory" class="level2">
<h2 class="anchored" data-anchor-id="a-cricket-decision-before-the-theory">A cricket decision before the theory</h2>
<p>A cricket team is defending 12 runs in the final over.</p>
<p>The captain must choose one of three bowlers:</p>
<ul>
<li>a fast bowler;</li>
<li>a spinner;</li>
<li>a medium-pace bowler.</li>
</ul>
<p>The batting side may respond aggressively or may focus on rotating the strike.</p>
<section id="think-for-one-minute" class="level3 panel">
<h3 class="anchored" data-anchor-id="think-for-one-minute">Think for one minute</h3>
<p><strong>Question:</strong> Which bowler should the captain choose?</p>
<p>Do not calculate anything yet.</p>
<p>What information would you want before making the decision?</p>
</section>
<section id="class-discussion" class="level3">
<h3 class="anchored" data-anchor-id="class-discussion">Class discussion</h3>
<p>Possible answers include:</p>
<ul>
<li>How has each bowler performed against aggressive batting?</li>
<li>How has each bowler performed when batters rotate the strike?</li>
<li>What is the pitch like?</li>
<li>Is one bowler more likely to concede boundaries?</li>
<li>Is one bowler better at limiting singles?</li>
<li>What is the estimated chance of successfully defending the target?</li>
</ul>
<p>The key point is simple:</p>
<blockquote class="blockquote">
<p>A decision is made <strong>now</strong>, but its consequence often depends on something that happens <strong>later</strong> and is not fully under our control.</p>
</blockquote>
<p>That is the setting in which decision theory becomes useful.</p>
<hr>
</section>
</section>
</section>
<section id="what-is-statistical-decision-theory" class="level1">
<h1>2. What is statistical decision theory?</h1>
<p>Statistical decision theory provides a structured way to make choices when outcomes depend partly on uncertain future conditions.</p>
<p>In this course, we will represent a decision problem using three basic ingredients:</p>
<ol type="1">
<li><strong>Decision alternatives</strong></li>
<li><strong>States of nature</strong></li>
<li><strong>Consequences</strong></li>
</ol>
<p>A fourth ingredient, <strong>available information</strong>, becomes increasingly important later when we study risk, Bayesian updating, and the value of information.</p>
<section id="core-decision-structure" class="level3 panel">
<h3 class="anchored" data-anchor-id="core-decision-structure">Core decision structure</h3>
<p><strong>Action + State of nature → Consequence</strong></p>
</section>
<hr>
</section>
<section id="anatomy-of-a-decision-problem" class="level1">
<h1>3. Anatomy of a decision problem</h1>
<section id="decision-alternatives" class="level2">
<h2 class="anchored" data-anchor-id="decision-alternatives">3.1 Decision alternatives</h2>
<p>A <strong>decision alternative</strong> is an action available to the decision maker.</p>
<p>The decision maker can choose among the alternatives.</p>
<section id="cricket-example" class="level3">
<h3 class="anchored" data-anchor-id="cricket-example">Cricket example</h3>
<p>Suppose a captain must choose a bowler for the final over.</p>
<ul>
<li>(A_1): Fast bowler</li>
<li>(A_2): Spin bowler</li>
<li>(A_3): Medium-pace bowler</li>
</ul>
<p>These are decision alternatives because the captain controls the choice.</p>
</section>
<section id="quick-question" class="level3 panel">
<h3 class="anchored" data-anchor-id="quick-question">Quick question</h3>
<p>Which of the following is a decision alternative?</p>
<ol type="1">
<li>The batter attacks</li>
<li>The pitch offers turn</li>
<li>The captain selects the spinner</li>
<li>The batting side scores 10 runs</li>
</ol>
<p><strong>Answer:</strong> 3. The captain selects the spinner.</p>
</section>
<hr>
</section>
<section id="states-of-nature" class="level2">
<h2 class="anchored" data-anchor-id="states-of-nature">3.2 States of nature</h2>
<p>A <strong>state of nature</strong> is a possible future condition that affects the consequence of a decision but is not controlled by the decision maker.</p>
<section id="cricket-example-1" class="level3">
<h3 class="anchored" data-anchor-id="cricket-example-1">Cricket example</h3>
<p>Suppose the captain chooses the final-over bowler.</p>
<p>Possible states of nature could be:</p>
<ul>
<li>(S_1): The batter attacks aggressively</li>
<li>(S_2): The batter focuses on strike rotation</li>
</ul>
<p>The captain chooses the bowler.</p>
<p>The captain does not control how the batter responds.</p>
<p>So:</p>
<ul>
<li><strong>Bowler choice = decision alternative</strong></li>
<li><strong>Batter response = state of nature</strong></li>
</ul>
</section>
<section id="athletics-example" class="level3">
<h3 class="anchored" data-anchor-id="athletics-example">Athletics example</h3>
<p>A 1500 m runner must decide on a pacing strategy.</p>
<p>Possible alternatives:</p>
<ul>
<li>(A_1): Fast early pace</li>
<li>(A_2): Even pace</li>
<li>(A_3): Conservative start with fast finish</li>
</ul>
<p>Possible states of nature:</p>
<ul>
<li>(S_1): Competitors make the race fast</li>
<li>(S_2): Competitors make the race tactical and slow</li>
</ul>
<p>The athlete controls the race plan but does not control the pace chosen by the rest of the field.</p>
</section>
<section id="volleyball-example" class="level3">
<h3 class="anchored" data-anchor-id="volleyball-example">Volleyball example</h3>
<p>A volleyball team is receiving serve at 23–23.</p>
<p>The coach may choose:</p>
<ul>
<li>(A_1): Middle attack</li>
<li>(A_2): Outside attack</li>
<li>(A_3): Back-row attack</li>
</ul>
<p>Possible states of nature:</p>
<ul>
<li>(S_1): Opponent commits the middle block</li>
<li>(S_2): Opponent forms a strong outside double block</li>
<li>(S_3): Opponent uses a balanced block</li>
</ul>
<p>The attacking team controls its own choice.</p>
<p>The opponent’s defensive response is not under its control.</p>
<hr>
</section>
</section>
<section id="consequences" class="level2">
<h2 class="anchored" data-anchor-id="consequences">3.3 Consequences</h2>
<p>A <strong>consequence</strong> is the result obtained when a particular alternative is chosen and a particular state of nature occurs.</p>
<p>The consequence might be expressed as:</p>
<ul>
<li>runs conceded;</li>
<li>probability of winning;</li>
<li>points won;</li>
<li>race time;</li>
<li>expected medal probability;</li>
<li>injury risk;</li>
<li>expected performance score;</li>
<li>or another quantity relevant to the decision.</li>
</ul>
<p>We denote the consequence of choosing alternative (A_i) when state (S_j) occurs by (C_{ij}).</p>
<p>For example:</p>
<ul>
<li>(A_2): Spin bowler</li>
<li>(S_1): Batter attacks aggressively</li>
</ul>
<p>Then (C_{21}) is the consequence of using the spinner when the batter attacks aggressively.</p>
<hr>
</section>
</section>
<section id="the-four-step-decision-theory-approach" class="level1">
<h1>4. The four-step decision-theory approach</h1>
<p>A useful decision-theory workflow is:</p>
<div class="panel">
<section id="step-1-list-the-viable-alternatives" class="level3">
<h3 class="anchored" data-anchor-id="step-1-list-the-viable-alternatives">Step 1: List the viable alternatives</h3>
<p>Identify the actions available to the decision maker.</p>
</section>
<section id="step-2-identify-the-possible-future-events" class="level3">
<h3 class="anchored" data-anchor-id="step-2-identify-the-possible-future-events">Step 2: Identify the possible future events</h3>
<p>List the relevant states of nature.</p>
</section>
<section id="step-3-construct-a-payoff-or-loss-table" class="level3">
<h3 class="anchored" data-anchor-id="step-3-construct-a-payoff-or-loss-table">Step 3: Construct a payoff or loss table</h3>
<p>Record the consequence for each action-state combination.</p>
</section>
<section id="step-4-select-an-appropriate-decision-criterion" class="level3">
<h3 class="anchored" data-anchor-id="step-4-select-an-appropriate-decision-criterion">Step 4: Select an appropriate decision criterion</h3>
<p>Choose a rule for comparing the alternatives.</p>
<p>The formal criteria are introduced in later weeks.</p>
</section>
</div>
<p>A useful schematic representation is:</p>
<section id="basic-decision-structure" class="level3 panel">
<h3 class="anchored" data-anchor-id="basic-decision-structure">Basic decision structure</h3>
<p><strong>Alternatives + States of nature → Consequences</strong></p>
</section>
<p>The decision rule then tells us how those consequences should be compared.</p>
<hr>
</section>
<section id="cricket-example-final-over-bowling-decision" class="level1">
<h1>5. Cricket example: final-over bowling decision</h1>
<p>Suppose the coaching staff summarize recent match data and estimate the <strong>expected runs conceded</strong> under different batter responses.</p>
<p>The captain must choose one bowler for the final over.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bowling decision</th>
<th style="text-align: right;">Batter attacks</th>
<th style="text-align: right;">Batter rotates strike</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fast bowler</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Spin bowler</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td>Medium pace</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
<section id="identify-the-components" class="level2">
<h2 class="anchored" data-anchor-id="identify-the-components">Identify the components</h2>
<section id="decision-alternatives-1" class="level3">
<h3 class="anchored" data-anchor-id="decision-alternatives-1">Decision alternatives</h3>
<ul>
<li>(A_1): Fast bowler</li>
<li>(A_2): Spin bowler</li>
<li>(A_3): Medium pace</li>
</ul>
</section>
<section id="states-of-nature-1" class="level3">
<h3 class="anchored" data-anchor-id="states-of-nature-1">States of nature</h3>
<ul>
<li>(S_1): Batter attacks</li>
<li>(S_2): Batter rotates strike</li>
</ul>
</section>
<section id="consequence" class="level3">
<h3 class="anchored" data-anchor-id="consequence">Consequence</h3>
<p>Expected runs conceded.</p>
<p>Here, <strong>smaller values are preferred</strong>.</p>
<p>So the table behaves like a <strong>loss table</strong>.</p>
<hr>
</section>
</section>
<section id="how-to-read-the-table" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-the-table">How to read the table</h2>
<p>If the captain chooses the spinner and the batter attacks, then:</p>
<p>[ C_{21}=8 ]</p>
<p>Interpretation:</p>
<blockquote class="blockquote">
<p>If the captain chooses the spinner and the batter attacks, the expected number of runs conceded is 8.</p>
</blockquote>
<p>Similarly:</p>
<p>[ C_{12}=7 ]</p>
<p>Interpretation:</p>
<blockquote class="blockquote">
<p>If the captain chooses the fast bowler and the batter rotates the strike, the expected number of runs conceded is 7.</p>
</blockquote>
<section id="stop-and-interpret" class="level3 panel">
<h3 class="anchored" data-anchor-id="stop-and-interpret">Stop and interpret</h3>
<ol type="1">
<li>Which bowler performs best if the batter attacks?</li>
<li>Which bowler performs best if the batter rotates the strike?</li>
<li>Which bowler has the largest possible expected runs conceded?</li>
<li>Can we choose the overall best bowler from this table alone?</li>
</ol>
<p><strong>Answers</strong></p>
<ol type="1">
<li>Spin bowler, with 8 expected runs conceded.</li>
<li>Fast bowler, with 7 expected runs conceded.</li>
<li>Fast bowler, with 12 expected runs conceded.</li>
<li>Not yet. We still need a rule for comparing alternatives when the future batting response is unknown.</li>
</ol>
</section>
<hr>
</section>
</section>
<section id="payoff-and-loss-formulations" class="level1">
<h1>6. Payoff and loss formulations</h1>
<p>The same sports decision can be expressed in different ways depending on the consequence being measured.</p>
<section id="cricket-as-a-loss-problem" class="level2">
<h2 class="anchored" data-anchor-id="cricket-as-a-loss-problem">Cricket as a loss problem</h2>
<p>If the consequence is <strong>runs conceded</strong>, smaller values are preferred.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bowling decision</th>
<th style="text-align: right;">Batter attacks</th>
<th style="text-align: right;">Batter rotates strike</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fast bowler</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Spin bowler</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td>Medium pace</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
<p>This is naturally interpreted as a <strong>loss table</strong>.</p>
</section>
<section id="cricket-as-a-payoff-problem" class="level2">
<h2 class="anchored" data-anchor-id="cricket-as-a-payoff-problem">Cricket as a payoff problem</h2>
<p>Suppose the analyst instead estimates the <strong>probability of successfully defending the target</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bowling decision</th>
<th style="text-align: right;">Batter attacks</th>
<th style="text-align: right;">Batter rotates strike</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fast bowler</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.71</td>
</tr>
<tr class="even">
<td>Spin bowler</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="odd">
<td>Medium pace</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.63</td>
</tr>
</tbody>
</table>
<p>Now larger values are preferred.</p>
<p>This is a <strong>payoff table</strong>.</p>
<div class="note">
<p>The underlying decision problem may be similar, but the direction of preference changes with the consequence measure.</p>
<ul>
<li>Runs conceded: lower is better.</li>
<li>Probability of winning: higher is better.</li>
</ul>
</div>
<hr>
</section>
</section>
<section id="athletics-example-pacing-strategy-in-a-1500-m-race" class="level1">
<h1>7. Athletics example: pacing strategy in a 1500 m race</h1>
<p>Suppose a 1500 m runner must select a race strategy before the event.</p>
<p>The likely race conditions are:</p>
<ul>
<li>(S_1): Fast race set by competitors</li>
<li>(S_2): Slow tactical race</li>
</ul>
<p>Suppose the consequence is <strong>finishing time in seconds</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Race strategy</th>
<th style="text-align: right;">Fast race</th>
<th style="text-align: right;">Slow tactical race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fast start</td>
<td style="text-align: right;">222</td>
<td style="text-align: right;">230</td>
</tr>
<tr class="even">
<td>Even pace</td>
<td style="text-align: right;">224</td>
<td style="text-align: right;">225</td>
</tr>
<tr class="odd">
<td>Conservative start</td>
<td style="text-align: right;">231</td>
<td style="text-align: right;">221</td>
</tr>
</tbody>
</table>
<p>Here, <strong>smaller values are preferred</strong>.</p>
<section id="class-questions" class="level3">
<h3 class="anchored" data-anchor-id="class-questions">Class questions</h3>
<ol type="1">
<li>What are the decision alternatives?</li>
<li>What are the states of nature?</li>
<li>What is the consequence?</li>
<li>Which strategy is best if the race is known to be fast?</li>
<li>Which strategy is best if the race is known to be slow?</li>
<li>Can one strategy be selected before the race condition is known?</li>
</ol>
</section>
<section id="answers" class="level3">
<h3 class="anchored" data-anchor-id="answers">Answers</h3>
<ol type="1">
<li>Fast start, even pace, conservative start.</li>
<li>Fast race and slow tactical race.</li>
<li>Finishing time in seconds.</li>
<li>Fast start, because 222 seconds is the smallest time.</li>
<li>Conservative start, because 221 seconds is the smallest time.</li>
<li>Not from this table alone. We still need a decision criterion.</li>
</ol>
</section>
<section id="the-same-athletics-problem-using-a-payoff" class="level2">
<h2 class="anchored" data-anchor-id="the-same-athletics-problem-using-a-payoff">The same athletics problem using a payoff</h2>
<p>Suppose instead the analysts estimate the probability of finishing in the top three.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Race strategy</th>
<th style="text-align: right;">Fast race</th>
<th style="text-align: right;">Tactical race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fast start</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="even">
<td>Even pace</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.33</td>
</tr>
<tr class="odd">
<td>Conservative start</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.49</td>
</tr>
</tbody>
</table>
<p>Now larger values are preferred.</p>
<p>This immediately shows an important feature of decision problems:</p>
<blockquote class="blockquote">
<p>The action that looks best depends on the state of nature.</p>
</blockquote>
<p>There is no single strategy that dominates in both race conditions.</p>
<hr>
</section>
</section>
<section id="volleyball-example-1" class="level1">
<h1>8. Volleyball example</h1>
<p>Suppose the setter must choose an attacking option late in a close set.</p>
<p>The consequence is the estimated <strong>probability of winning the rally</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Attack</th>
<th style="text-align: right;">Middle block</th>
<th style="text-align: right;">Outside double block</th>
<th style="text-align: right;">Balanced block</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Middle attack</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.47</td>
</tr>
<tr class="even">
<td>Outside attack</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.45</td>
</tr>
<tr class="odd">
<td>Back-row attack</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.42</td>
</tr>
</tbody>
</table>
<p>Let:</p>
<ul>
<li>(A_1): Middle attack</li>
<li>(A_2): Outside attack</li>
<li>(A_3): Back-row attack</li>
</ul>
<p>and:</p>
<ul>
<li>(S_1): Middle commit block</li>
<li>(S_2): Outside double block</li>
<li>(S_3): Balanced block</li>
</ul>
<p>Then:</p>
<p>[ C_{21}=0.59 ]</p>
<p>Interpretation:</p>
<blockquote class="blockquote">
<p>If the team uses the outside attack and the opponent commits to the middle block, the estimated probability of winning the rally is 0.59.</p>
</blockquote>
<p>Similarly:</p>
<p>[ C_{32}=0.55 ]</p>
<p>Interpretation:</p>
<blockquote class="blockquote">
<p>If the team uses the back-row attack and the opponent forms an outside double block, the estimated probability of winning the rally is 0.55.</p>
</blockquote>
<div class="note">
<p>In sports analytics, the consequence may itself be an <strong>estimated statistical quantity</strong>, such as a win probability. Later in the course we will study how additional information can change those estimates and therefore change the decision.</p>
</div>
<hr>
</section>
<section id="formulating-a-decision-problem" class="level1">
<h1>9. Formulating a decision problem</h1>
<p>Before doing any calculation, write the problem in a structured form.</p>
<section id="template" class="level2">
<h2 class="anchored" data-anchor-id="template">Template</h2>
<p>For any sports decision problem, identify:</p>
<section id="decision-maker" class="level3">
<h3 class="anchored" data-anchor-id="decision-maker">Decision maker</h3>
<p>Who chooses the action?</p>
</section>
<section id="alternatives" class="level3">
<h3 class="anchored" data-anchor-id="alternatives">Alternatives</h3>
<p>What can be chosen?</p>
<p>Use notation such as (A_1, A_2, , A_m).</p>
</section>
<section id="states-of-nature-2" class="level3">
<h3 class="anchored" data-anchor-id="states-of-nature-2">States of nature</h3>
<p>What uncertain future conditions may occur?</p>
<p>Use notation such as (S_1, S_2, , S_n).</p>
</section>
<section id="consequences-1" class="level3">
<h3 class="anchored" data-anchor-id="consequences-1">Consequences</h3>
<p>What happens if (A_i) is selected and (S_j) occurs?</p>
<p>Use (C_{ij}) for the corresponding consequence.</p>
</section>
<section id="available-information" class="level3">
<h3 class="anchored" data-anchor-id="available-information">Available information</h3>
<p>What is currently known about the states of nature?</p>
<hr>
</section>
</section>
</section>
<section id="activity" class="level1">
<h1>10. Student activity</h1>
<section id="minute-activity-volleyball-serving-decision" class="level2 panel">
<h2 class="anchored" data-anchor-id="minute-activity-volleyball-serving-decision">8-minute activity: Volleyball serving decision</h2>
<p>A volleyball coach must decide whether to keep the current server or introduce a serving specialist late in the set.</p>
<p>Two possible reception states are considered:</p>
<ul>
<li>the opponent receives well;</li>
<li>the opponent receives poorly.</li>
</ul>
<p>The estimated probability of winning the rally is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Decision</th>
<th style="text-align: right;">Good opponent reception</th>
<th style="text-align: right;">Poor opponent reception</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Keep current server</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td>Use serving specialist</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.76</td>
</tr>
</tbody>
</table>
<section id="work-in-pairs" class="level3">
<h3 class="anchored" data-anchor-id="work-in-pairs">Work in pairs</h3>
<ol type="1">
<li>Identify the decision maker.</li>
<li>Identify the decision alternatives.</li>
<li>Identify the states of nature.</li>
<li>Identify the consequence.</li>
<li>Find (C_{12}).</li>
<li>Find (C_{21}).</li>
<li>Which action would be selected if good reception were known with certainty?</li>
<li>Which action would be selected if poor reception were known with certainty?</li>
<li>Can one action be selected for the next serve without using an additional decision criterion? Explain briefly.</li>
</ol>
</section>
</section>
<section id="suggested-answers" class="level3">
<h3 class="anchored" data-anchor-id="suggested-answers">Suggested answers</h3>
<p><strong>Decision maker</strong></p>
<p>The coach.</p>
<p><strong>Alternatives</strong></p>
<ul>
<li>(A_1): Keep current server</li>
<li>(A_2): Use serving specialist</li>
</ul>
<p><strong>States of nature</strong></p>
<ul>
<li>(S_1): Good reception</li>
<li>(S_2): Poor reception</li>
</ul>
<p><strong>Consequence</strong></p>
<p>Probability of winning the rally.</p>
<p>[ C_{12}=0.62 ]</p>
<p>and</p>
<p>[ C_{21}=0.35 ]</p>
<p>If good reception were known with certainty:</p>
<p>[ 0.43&gt;0.35 ]</p>
<p>so the current server would be preferred.</p>
<p>If poor reception were known with certainty:</p>
<p>[ 0.76&gt;0.62 ]</p>
<p>so the serving specialist would be preferred.</p>
<p>Before the reception state is known, the table alone does not provide a complete decision rule.</p>
<hr>
</section>
</section>
<section id="why-the-distinction-matters" class="level1">
<h1>11. Why the distinction matters</h1>
<p>A common mistake is to mix up an <strong>action</strong> with an <strong>event</strong>.</p>
<p>Consider:</p>
<blockquote class="blockquote">
<p>“The batter attacks.”</p>
</blockquote>
<p>That is not the captain’s decision. It is a possible state of nature.</p>
<p>Now consider:</p>
<blockquote class="blockquote">
<p>“The captain selects the spinner.”</p>
</blockquote>
<p>That is a decision alternative.</p>
<p>Similarly in athletics:</p>
<blockquote class="blockquote">
<p>“The race becomes tactical.”</p>
</blockquote>
<p>This is a state of nature.</p>
<p>But:</p>
<blockquote class="blockquote">
<p>“The athlete adopts an even pace.”</p>
</blockquote>
<p>This is a decision alternative.</p>
<p>The same distinction will matter throughout the course.</p>
<p>Later, probabilities may be attached to states of nature. Sample information may revise those probabilities. Utility may change how consequences are valued. But the underlying structure remains:</p>
<section id="remember" class="level3 panel">
<h3 class="anchored" data-anchor-id="remember">Remember</h3>
<p><strong>Action + State of nature → Consequence</strong></p>
</section>
<hr>
</section>
<section id="exit-check" class="level1">
<h1>12. Exit check</h1>
<p>Take the final four minutes individually.</p>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>A cricket captain chooses between spin and pace.</p>
<p>The pitch may turn sharply or remain flat.</p>
<p>Which is the <strong>state of nature</strong>?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pitch behaviour.</p>
</div>
</div>
</div>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>A 1500 m runner chooses between an aggressive and conservative pacing strategy.</p>
<p>The consequence is finishing time.</p>
<p>Should larger or smaller values be preferred?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Smaller values are preferred.</p>
</div>
</div>
</div>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<p>A volleyball coach chooses an attack strategy while the opponent’s block is uncertain.</p>
<p>Complete:</p>
<p><strong>Action + State of nature → ?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Consequence</strong></p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="after-class" class="level1">
<h1>After class</h1>
<section id="independent-learning" class="level2">
<h2 class="anchored" data-anchor-id="independent-learning">Independent learning</h2>
<p>Before Week 2:</p>
<ol type="1">
<li>Review the basic structure of a decision problem.</li>
<li>Create one sports example with:
<ul>
<li>at least two alternatives;</li>
<li>at least two states of nature;</li>
<li>one numerical consequence for every action-state combination.</li>
</ul></li>
<li>State clearly whether the consequence should be maximized or minimized.</li>
<li>Write one sentence explaining why your example involves uncertainty.</li>
</ol>
</section>
<section id="next-week" class="level2">
<h2 class="anchored" data-anchor-id="next-week">Next week</h2>
<p><strong>Week 02: Decision-Making Environments</strong></p>
<p>We will distinguish decisions under:</p>
<ul>
<li>certainty;</li>
<li>uncertainty;</li>
<li>risk.</li>
</ul>
<p>We will then use that distinction to decide what information is available before choosing a decision rule.</p>
<hr>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<p>Gupta, P. K., Hira, D. S., &amp; Kamboj, A. (2012). <em>Introduction to Operations Research</em>. S Chand and Company Limited. Chapter 9: Decision Theory, pp.&nbsp;635–711.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>