---
title: "MSc in Applied Statistics - Foundation: Probability and Distribution Theory"
author: "Dr. Rajitha M. Silva"
output: html_document
---

# Course Information

|                    |                                     |
|--------------------|-------------------------------------|
| **Course Title:**  | Probability and Distribution Theory |
| **Pre-requisite:** | BSc Degree                          |

------------------------------------------------------------------------

# Aim of the Course

This course establishes the fundamentals of probability theory. It supports learning in statistical inference, risk evaluation, actuarial modeling, and various forecasting fields such as weather prediction, sports outcomes, and finance. It is also a prerequisite for advanced modules in probability and statistics.

------------------------------------------------------------------------

# Learning Activities & Weekly Breakdown

::: {style="text-align: center;"}
+---------------------------------------------------------------------+
| **Topic**                                                           |
+=====================================================================+
| [Elements of Probability](lesson1.html)                             |
+---------------------------------------------------------------------+
| [Event Operations](lesson2.html)                                    |
+---------------------------------------------------------------------+
| [Methods of Probability](https://sportsanalyzr.shinyapps.io/week3/) |
+---------------------------------------------------------------------+
| [Conditional Probability](lesson4.html)                             |
+---------------------------------------------------------------------+
| [Probability Rules](lesson5.html)                                   |
+---------------------------------------------------------------------+
| Random Variables                                                    |
+---------------------------------------------------------------------+
| Events with Random Variables                                        |
+---------------------------------------------------------------------+
| Distributions                                                       |
+---------------------------------------------------------------------+
| Probability Calculations                                            |
+---------------------------------------------------------------------+
| Mean & Variance                                                     |
|                                                                     |
| Some Probability Distributions                                      |
+---------------------------------------------------------------------+
|                                                                     |
+---------------------------------------------------------------------+
|                                                                     |
+---------------------------------------------------------------------+
:::

*T = Theory, IL = Independent Learning*

------------------------------------------------------------------------

# Intended Learning Outcomes (ILOs)

By the end of this course, students will be able to:

1.  Describe events using set notation and sample spaces.\
2.  Formulate and identify events of interest.\
3.  Apply classical and empirical methods for calculating probability.\
4.  Explain and apply probability axioms.\
5.  Distinguish conditional from unconditional events.\
6.  Use rules of probability effectively.\
7.  Define and identify types of random variables.\
8.  Relate events to random variables.\
9.  Use pmf, pdf, cdf correctly.\
10. Calculate probabilities and descriptive measures from distributions.\
11. Define and interpret mean, median, variance, etc.\
12. Use known distributions for applications\
13. Use correct notation and terminology.\
14. Communicate clearly and coherently.\
15. Present clear and accurate solutions to problems.

------------------------------------------------------------------------

# References

-   Jay L. Devore, *Probability and Statistics for Engineering and Sciences*, Brooks/Cole.\
-   B.M.S.G. Banneheka, *Statistical Distribution Theory*, Open University of Sri Lanka.\
-   Class handouts and lecture notes.

------------------------------------------------------------------------

# Instructor

**Lecturer:** Dr. Rajitha M. Silva\
**Email:** [rsilva\@sjp.ac.lk](mailto:rsilva@sjp.ac.lk){.email}\

------------------------------------------------------------------------

*This course is effective from 19th May 2025.*
