---
title: "STA 472 2.0 Bayesian Inference"
output: 
  html_document:
    theme: cosmo
    highlight: tango
---

**Batch:** 2020/2021\
**Schedule:** Wednesday, 10:15 a.m. to 12.00 noon\
**Venue:** STAT Lab 2\
**Instructor:** Dr. Rajitha M. Silva\
**Department of Statistics, University of Sri Jayewardenepura**

------------------------------------------------------------------------

## Introduction

This course offers a practical and computational approach to Bayesian inference, focusing on simulation-based techniques for solving complex models.

Learning outcomes:

-   The foundations of Bayesian thinking\
-   Posterior analysis using simulation\
-   Markov Chain Monte Carlo (MCMC) methods\
-   Model comparison and convergence diagnostics\


All course materials will be published on this page.

------------------------------------------------------------------------

## Lecture Notes

All the lecture notes are based on the book named "[Bayes Rules! An Introduction to Applied Bayesian Modeling](https://www.bayesrulesbook.com/)" by Alicia A. Johnson, Miles Q. Ott, and Mine Dogucu. Please read the relevant chapter before the lecture.

> Click on each link to view the lecture content and downloadable code/handouts.

-   [Chapter 1: The Big (Bayesian) Picture](chapter1_notes.html)

-   [Chapter 2: Bayes Rule](chapter2.html)

-   [Chapter 3: The Beta-Binomial Bayesian Model](chapter3.html)

-   [Chapter 4: Balance and Sequentiality in Bayesian Analyses](chapter4.html)

------------------------------------------------------------------------

## Contact

For questions or clarifications, please reach out via email.
